# Deep Learning Con Tensorflow

Tomado del curso [Deep Learning con Tensorflow para Machine Learning e IA](https://www.udemy.com/course/tensorflow-python/) del profesor [Juan Gabriel Gomila Salas](https://github.com/joanby/tensorflow).

## Operaciones en el grafo de computación

In [1]:
import tensorflow as tf
session = tf.Session()

In [2]:
import numpy as np

In [4]:
x_vals = np.array([2.,4.,6.,8.,10.,12.])

In [6]:
x_data = tf.placeholder(tf.float32)

In [8]:
m_const = tf.constant(3.)

$$ y = mx = 3x $$

In [10]:
my_product = tf.multiply(m_const, x_data)
my_product

<tf.Tensor 'Mul_1:0' shape=<unknown> dtype=float32>

In [12]:
for x_val in x_vals:
    print(session.run(my_product, feed_dict = {x_data: x_val}))

6.0
12.0
18.0
24.0
30.0
36.0


In [13]:
print(session.run(my_product, feed_dict = {x_data: x_vals}))

[ 6. 12. 18. 24. 30. 36.]


In [14]:
session.run(tf.multiply(m_const, x_vals))

array([ 6., 12., 18., 24., 30., 36.], dtype=float32)

## Operaciones por capas

In [17]:
import tensorflow as tf
session = tf.Session()

In [18]:
import numpy as np

In [20]:
my_array = np.array([[1.,3.,5.,7.],
                    [-2.,0.,7.,6.],
                    [-6.,-1.,0.,3.]])
my_array

array([[ 1.,  3.,  5.,  7.],
       [-2.,  0.,  7.,  6.],
       [-6., -1.,  0.,  3.]])

In [21]:
x_vals = np.array([my_array, my_array+1])
x_vals

array([[[ 1.,  3.,  5.,  7.],
        [-2.,  0.,  7.,  6.],
        [-6., -1.,  0.,  3.]],

       [[ 2.,  4.,  6.,  8.],
        [-1.,  1.,  8.,  7.],
        [-5.,  0.,  1.,  4.]]])

In [29]:
x_data = tf.placeholder(tf.float32, shape=(3,None))

In [25]:
m1 = tf.constant([[1.],[0.],[-2.],[5.]])
m2 = tf.constant([[7.]])
a1 = tf.constant([[15.]])

$$(X\cdot m_1)m_2+a_1$$

In [31]:
prod1 = tf.matmul(x_data, m1)
prod2 = tf.matmul(prod1, m2)
add1 = tf.add(prod2, a1)

In [32]:
for x_val in x_vals:
    print(session.run(add1, feed_dict={x_data: x_val}))

[[197.]
 [113.]
 [ 78.]]
[[225.]
 [141.]
 [106.]]


## Trabajar con múltiples capas

In [46]:
import tensorflow as tf
import numpy as np
from tensorflow.python.framework import ops
ops.reset_default_graph()
session = tf.InteractiveSession()
# session = tf.Session()

C:\ProgramData\Miniconda3\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [47]:
x_shape = [1,4,4,1]
x_val = np.random.uniform(size = x_shape)
x_val

array([[[[0.06128026],
         [0.87156032],
         [0.72401941],
         [0.60112092]],

        [[0.8891606 ],
         [0.28728361],
         [0.83489501],
         [0.40807198]],

        [[0.7320763 ],
         [0.75241017],
         [0.79797285],
         [0.77101396]],

        [[0.76440585],
         [0.00251679],
         [0.54689621],
         [0.13860781]]]])

In [48]:
x_data = tf.placeholder(tf.float32, shape = x_shape)

In [49]:
my_filter = tf.constant(0.25, shape = [2,2,1,1])
my_strides = [1,2,2,1]
mov_avg_layer = tf.nn.conv2d(x_data, my_filter,my_strides, padding='SAME', name='Moving_Average_Wnd')

$$\frac{W-F+2P}{S}+1$$

- W : dimensión de entrada
- F: Dimensión del filtro
- P: Padding
- S: Stride

In [50]:
def custom_layer(input_matrix):
    input_matrix_squeezed  =tf.squeeze(input_matrix)
    A = tf.constant([[1.,2.],[3.,4.]])
    b = tf.constant(1., shape=[2,2])
    temp1 = tf.matmul(A, input_matrix_squeezed)
    temp2 = tf.add(temp1, b)
    return tf.sigmoid(temp2)

In [51]:
with tf.name_scope("Custom_layer") as scope:
    customlayer1 = custom_layer(mov_avg_layer) 

In [52]:
session.run(customlayer1, feed_dict={x_data: x_val})

array([[0.9341972 , 0.94099253],
       [0.9921033 , 0.9944067 ]], dtype=float32)

### Tensorboard

In [53]:
writer = tf.summary.FileWriter('multiple-layes', session.graph)
session.run(customlayer1, feed_dict={x_data: x_val})
writer.close()

## Funciones de pérdida en predicción

In [55]:
import tensorflow as tf
import matplotlib.pyplot as plt
session = tf.Session()

In [57]:
x_vals = tf.linspace(-1.,1.,500)
target = tf.constant(0.)

### Norma L2 (distancia Euclidiana)

$$L2(y_r, y_p) = \sqrt{\sum(y_r-y_p)^2}$$

In [65]:
l2_y_vals = tf.sqrt(tf.reduce_sum(tf.square(target-x_vals)))

In [69]:
l2_y_out = session.run(l2_y_vals)
print((l2_y_out**2)/2)

83.66733226343104


In [67]:
session.run(tf.nn.l2_loss(target-x_vals))

83.667336

### Norma L1

$$L1(y_r,y_p)=|y_r-y_p|$$

In [70]:
l1_y_vals = tf.abs(target-x_vals)

In [71]:
l1_y_out = session.run(l1_y_vals)

In [73]:
print(l1_y_out)

[1.         0.995992   0.99198395 0.98797596 0.98396796 0.9799599
 0.9759519  0.9719439  0.96793586 0.96392787 0.9599198  0.9559118
 0.9519038  0.94789577 0.94388777 0.9398798  0.9358717  0.9318637
 0.92785573 0.9238477  0.9198397  0.9158317  0.91182363 0.90781564
 0.90380764 0.8997996  0.8957916  0.8917836  0.88777554 0.88376755
 0.87975955 0.8757515  0.8717435  0.8677355  0.86372745 0.85971946
 0.8557114  0.8517034  0.8476954  0.84368736 0.83967936 0.8356713
 0.8316633  0.8276553  0.82364726 0.81963927 0.8156313  0.8116232
 0.8076152  0.8036072  0.7995992  0.7955912  0.7915832  0.7875751
 0.78356713 0.77955914 0.7755511  0.7715431  0.7675351  0.76352704
 0.75951904 0.75551105 0.751503   0.747495   0.743487   0.73947895
 0.73547095 0.73146296 0.7274549  0.72344685 0.7194389  0.71543086
 0.7114228  0.70741487 0.7034068  0.69939876 0.6953908  0.69138277
 0.6873747  0.6833667  0.6793587  0.67535067 0.6713427  0.6673347
 0.6633266  0.6593186  0.65531063 0.6513026  0.6472946  0.6432866
 0.

### Pseudo-Huber

$$PH(y_r,y_p) = \delta^2 \cdot \sqrt{1+\left(\frac{y_r-y_p}{\delta}\right)^2}-1, \delta > 0$$

In [75]:
delta1 = tf.constant(0.25)
phuber1_y_vals = tf.multiply(tf.square(delta1), tf.sqrt(1.+tf.square((target-x_vals)/delta1))-.1)

In [76]:
phuber1_y_out = session.run(phuber1_y_vals)
print(phuber1_y_out)

[0.2514441  0.25047213 0.2495004  0.24852893 0.24755764 0.24658659
 0.24561578 0.24464527 0.24367496 0.2427049  0.24173515 0.24076563
 0.23979636 0.23882735 0.23785861 0.23689017 0.23592193 0.23495403
 0.23398636 0.23301901 0.23205197 0.23108518 0.23011866 0.22915247
 0.2281866  0.227221   0.22625573 0.22529078 0.22432612 0.22336179
 0.22239776 0.2214341  0.22047074 0.21950775 0.21854503 0.21758276
 0.21662077 0.21565916 0.2146979  0.213737   0.21277645 0.21181628
 0.21085653 0.20989713 0.20893814 0.20797952 0.2070213  0.20606348
 0.20510611 0.20414913 0.20319253 0.20223643 0.20128073 0.20032547
 0.19937061 0.19841626 0.19746235 0.19650891 0.19555594 0.19460341
 0.19365141 0.1926999  0.19174886 0.19079834 0.18984833 0.18889885
 0.18794988 0.18700147 0.18605357 0.18510623 0.1841595  0.18321328
 0.18226765 0.1813226  0.18037817 0.17943433 0.17849112 0.17754848
 0.17660652 0.17566518 0.1747245  0.17378448 0.17284511 0.17190646
 0.17096847 0.17003122 0.16909468 0.16815884 0.16722377 0.1662